---

# 2. NumPy

It is very important that you google and consult the documentation. If you didn't install it, now is a good time. When we want to use a library, we must first import it.

Now our work environment knows that if we put something like __np.__ it means that this functionality must be found in NumPy. Important: If the library was NOT installed correctly, you will get an error message.

The main data type that NumPy works on are arrays. Arrays are similar to lists and can actually be created from them.

In [ ]:
import numpy as np

In [ ]:
my_list = [0,1,2,3,4,5]
array = np.array(my_list)

print(my_list)
print(array)
print()

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]



But they are more than a list. Some things that couldn't be done with lists can now be done with fixes. Remember that adding a number to the entire list was not allowed.

In [ ]:
my_list + 1

TypeError: ignored

But now with the arrays yes!

In [ ]:
array + 1

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(array - 5)
print(array - 2)
print(array * 4)
print(array ** 2)

[-5 -4 -3 -2 -1  0]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


**TODO:** Except for multiplication, none was allowed in lists. What does multiplication do for a list?

**Concatenation as well as string**

In [ ]:
my_list= ["Hello"]
print([my_list]*3)
print("Hello"*3)

[['Hello'], ['Hello'], ['Hello']]
HelloHelloHello


## Array Creation

While we can create arrays from lists, NumPy comes with many features to do so. Let's see some.

A widely used one is __np.arange()__. Check your documentation. Alternatively, in a code cell, type __np.arange__ and press __shift + tab__. That way, help will appear.

Play around with the example below.

In [ ]:
array = np.arange(3, 20, 2)
print(array)

[ 3  5  7  9 11 13 15 17 19]


In [ ]:
array2 = np.arange(10,21,5)
print(array2)

[10 15 20]


In [ ]:
array3= np.arange(10,0,-1)
print(array3)

[10  9  8  7  6  5  4  3  2  1]


**TODO:**
Investigate and create examples with the following functions

* np.linspace
* np.arange
* np.zeros and np.ones

In [ ]:
array1 = np.arange(0,51,10)
print(array1)
print("El shape de array1 es:", array1.shape)
print("El size del array1 es:",array1.size,"\n",sep="")

array2 = np.linspace(1,101,49)
print(array2)
print("El shape de array2 es:", array2.shape)
print("El size del array2 es:",array2.size,"\n",sep="")

array3= np.zeros((3,4), dtype=int)
print(array3)
print("El shape de array3 es:", array3.shape)
print("El size del array3 es:",array3.size,"\n",sep="")

array4 = np.ones((2,10),dtype=str)
print(array4)
print("El shape de array4 es:", array4.shape)
print("El size del array4 es:",array4.size,"\n",sep="")

[ 0 10 20 30 40 50]
El shape de array1 es: (6,)
El size del array1 es:6

[  1.           3.08333333   5.16666667   7.25         9.33333333
  11.41666667  13.5         15.58333333  17.66666667  19.75
  21.83333333  23.91666667  26.          28.08333333  30.16666667
  32.25        34.33333333  36.41666667  38.5         40.58333333
  42.66666667  44.75        46.83333333  48.91666667  51.
  53.08333333  55.16666667  57.25        59.33333333  61.41666667
  63.5         65.58333333  67.66666667  69.75        71.83333333
  73.91666667  76.          78.08333333  80.16666667  82.25
  84.33333333  86.41666667  88.5         90.58333333  92.66666667
  94.75        96.83333333  98.91666667 101.        ]
El shape de array2 es: (49,)
El size del array2 es:49

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
El shape de array3 es: (3, 4)
El size del array3 es:12

[['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']]
El shape de array4 es: (2, 10)
El size del array4 es:20

